Browser = Chrome
URL_ChatBot = https://criticalriveruat.devsproject.com/
FrontEnd_URL=https://website-chatbot-frontend-dev.nicecliff-0aaf3e3b.eastus.azurecontainerapps.io/
CSAT_Uat_Url=https://crsurveyapp-frontend-uat.delightfulwave-3f548879.eastus.azurecontainerapps.io/
CSAT_Dev_Url=https://crsurveyapp5-frontend-dev.ashyhill-3eede200.eastus.azurecontainerapps.io
ReportName = CrChatBot.html