Browser = Chrome
URL = https://criticalriveruat.devsproject.com/
FrontEnd_URL=https://website-chatbot-frontend-dev.nicecliff-0aaf3e3b.eastus.azurecontainerapps.io/
CSAT_Url=https://crsurveyapp-frontend-uat.delightfulwave-3f548879.eastus.azurecontainerapps.io/
  
ReportName = CrChatBot.html