Browser = Chrome
URL_ChatBot = https://criticalriveruat.devsproject.com/
FrontEnd_URL=https://website-chatbot-frontend-dev.nicecliff-0aaf3e3b.eastus.azurecontainerapps.io/
CSAT_Uat_Url=https://crsurveyapp5-frontend-uat.bluedune-79d990c1.centralus.azurecontainerapps.io
CSAT_Dev_Url=https://crsurveyapp5-frontend-dev.ashyhill-3eede200.eastus.azurecontainerapps.io
ReportName = CrChatBot.html
L_And_D_DevUrl=https://crlndportal-frontend-dev.salmonground-e485a14f.eastus.azurecontainerapps.io/login
L_And_D_UatUrl=https://crlndportal-frontend-uat.victoriousbeach-e8651211.eastus.azurecontainerapps.io/login
